export const USERS = {
  LOADING: "LOADING",
  ERROR: "ERROR",
  DONE: "DONE"
};

export const USERDETAIL = {
  LOADING: "USERDETAIL.LOADING",
  ERROR: "USERDETAIL.ERROR",
  DONE: "USERDETAIL.DONE"
};

export const USERPOSTS = {
  LOADING: "USERPOSTS.LOADING",
  ERROR: "USERPOSTS.ERROR",
  DONE: "USERPOSTS.DONE"
};

export const POST = {
  LOADING: "POST.LOADING",
  ERROR: "POST.ERROR",
  DONE: "POST.DONE"
};

export const COMMENTS = {
  LOADING: "COMMENTS.LOADING",
  ERROR: "COMMENTS.ERROR",
  DONE: "COMMENTS.DONE"
};

export const USERALBUMS = {
  LOADING: "USERALBUMS.LOADING",
  ERROR: "USERALBUMS.ERROR",
  DONE: "USERALBUMS.DONE"
};

export const ALBUM = {
  LOADING: "ALBUM.LOADING",
  ERROR: "ALBUM.ERROR",
  DONE: "ALBUM.DONE"
};

export const PHOTOS = {
  LOADING: "PHOTOS.LOADING",
  ERROR: "PHOTOS.ERROR",
  DONE: "PHOTOS.DONE"
};
